version: 2

build:
  os: ubuntu-20.04
  language: nodejs
  nodejs:
    version: 16
    install:
      - pip install mkdocs
      - pip install mkdocs-github

  tools:
    python: "3.9"  

commands:
  - mkdocs build  

sphinx:
  configuration: docs/source/conf.py
