version: 2

build:
  os: ubuntu-20.04
  language: nodejs
  nodejs:
    version: 16
    install:
      - pip install mkdocs
      - pip install mkdocs-github

  commands:
    - mkdocs build 

sphinx: false
