site_name: Closure Next Documentation
site_url: https://closure-next.github.io
site_description: Closure Library rewritten in TypeScript
theme:
  name: github
  custom_dir: theme
  palette:
    primary: 'blue'
    accent: 'yellow'

nav:
  - Home: index.md
  - Core API: api/core.md
  - Framework Integration Guides: guides/integrations.md
  - Implementation Details: implementation/details.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - attr_list

plugins:
  - search

repo_url: https://github.com/MilesONerd/closure-next
